config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # / 으로 들어온 url에 관한 처리를 core/urls.py 에서 찾아 mapping 하라는 의미 이다.
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

# 내가 개발모드라면(Not production)
if settings.DEBUG:  # static 함수를 보면 (url, 사진저장폴더경로)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from unicodedata import name
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # name: 나중에 해당 url을 처리할때 url전부를 하드코딩하는 것 이 아니라, 간편하게 해당 url을 지칭할 수 있다.
    path("", room_views.HomeView.as_view(), name="home")
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

# rooms/ 하위 url 경로에 int값이 오면(pk 변수에 대입) views.room_detail의 요청 파라미터로 pk를 넘겨줌
urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.room_detail, name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse  # 지정한 url name을 return 하기위해
from django.utils import timezone
from dateutil import relativedelta
from django_countries.fields import CountryField
from core import models as core_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "Room Type"
        # ordering = ["created"] # 객체들의 정렬 순서를 정할 수 있음


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facilty Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"


# room의 사진을 위한 클래스
class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(
        upload_to="room_photos"
    )  # uploads 폴더안에 어떤 폴더에다가 photo를 업로드 할 것인지
    # Room은 사진을 여러개, 한 사진은 하나의 Room에 해당
    # Room 클래스(객체)를 String으로도 받을 수 있음
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    # user model을 외래키로 연결(다대일)
    # related_name: 외래키로 연결된 User가 Room을 찾기위한 방법(room_set의 이름 변경)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    # RoomType을 다대다로
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    # Room 객체를 문자열로 어떻게 보이게 할 것인지.
    def __str__(self):
        return self.name

    # admin, view 모든 곳에서 save시에 수행됨
    def save(self, *args, **kwargs):
        self.city = self.city.title()  # city의 단어 앞글자만 대문자로
        super().save(*args, **kwargs)  # 진짜 save(저장) method 호출

    # admon 패널에 해당 room 객체가 어떻게 화면에 보이는지
    def get_absolute_url(self):
        # urlname으로 지정한 곳으로 이동(kwargs: 매개변수 포함)
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        # review 모델에 있는 room(foreign key로 연결) 필드에서 reviews를 읽어옴
        all_reviews = self.reviews.all()
        try:
            all_ratings = 0
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        except ZeroDivisionError:  # 리뷰가 하나도 없을때의 예외처리
            return 0

    # 첫번째 사진 가져오는 함수
    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        today = timezone.localtime(timezone.now()).date()
        nextmonth = today + relativedelta.relativedelta(months=1)
        this_month = Calendar(today.year, today.month)
        next_month = Calendar(nextmonth.year, nextmonth.month)
        return [this_month, next_month]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    # form에 나타낼 model들
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator, Page
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """Homeview Definition"""

    # ListView가 아래 model(Room 객체들)을 List 해줌
    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"  # 불러오는 model object의 이름 설정


# Class Based View
# class RoomDetail(DetailView):  # DetailView는 기본적으로 url argument로 pk를 찾음

#     """RoomDetail Definition"""

#     # view 한테 무슨 model을 원하는지 알려줘야함
#     model = models.Room


# Function Based View
@login_required
def room_detail(request, pk):  # 요청 파라미터로부터 온 pk도 같이 넘겨받음
    try:
        room = models.Room.objects.get(pk=pk)  # 매개변수로 넘어온 pk의 room 객체 가져오기
        return render(request, "rooms/room_detail.html", {"room": room})
    except models.Room.DoesNotExist:  # 매개변수로 넘어온 pk에 해당되는 room 객체가 없으면
        raise Http404()  # 404 page 띄우기


class SearchView(View):
    """Room search view"""

    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                populated_data = form.cleaned_data

                city = populated_data.get("city")
                country = populated_data.get("country")
                room_type = populated_data.get("room_type")
                price = populated_data.get("price")
                guests = populated_data.get("guests")
                bedrooms = populated_data.get("bedrooms")
                beds = populated_data.get("beds")
                baths = populated_data.get("baths")
                instant_book = populated_data.get("instant_book")
                superhost = populated_data.get("superhost")
                amenities = populated_data.get("amenities")
                facilities = populated_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                qs = models.Room.objects.filter(**filter_args)

                for amenity in amenities:
                    qs = qs.filter(amenities=amenity)

                for facility in facilities:
                    qs = qs.filter(facilities=facility)

                qs = qs.order_by("-created")

                paginator = Paginator(qs, 10)

                page = int(request.GET.get("page", 1))

                rooms = paginator.get_page(page)

        else:

            form = forms.SearchForm()
            rooms = Page(
                [], number=0, paginator=Paginator([], 10)
            )  # just an empty Page for type match with if-case

        return render(request, "rooms/search.html", {"form": form, "rooms": rooms})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    # get_object() : room을 찾아서 보여줌
    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


# 로그인 한 사람만 접근 가능한 DetailView
class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        photo = models.Photo.objects.get(pk=photo_pk)
        if not (room.host.pk == user.pk and user.pk == photo.room.host.pk):
            messages.error(request, "Cant delete that photo")
        else:
            photo.delete()
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"  # pk라는 이름이 아닌 다른 pk를 못찾기에 추가
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})

    def get_object(self, queryset=None):
        photo = super().get_object(queryset=queryset)
        if photo.room.host.pk != self.request.user.pk:
            raise Http404()
        return photo


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        # many to many 필드 저장하기(db에 먼저 저장 후 호출해야한다)
        form.save_m2m()
        messages.success(self.request, "Room Uploaded")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends 'base.html' %}


{% block page_name %}
    Home
{% endblock page_name %}
    

{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By: {{room.host.username}}
    {% if room.host.superhost %}
        (superhost)
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenities.all %}
        <li>{{a}}</li>    
    {% endfor %}
    </ul> 

    <h3>Facilities</h3>
    <ul>
    {% for f in room.facilities.all %}
        <li>{{f}}</li>    
    {% endfor %}
    </ul>      

    <h3>House Rules</h3>
    <ul>
    {% for h in room.house_rules.all %}
        <li>{{h}}</li>    
    {% endfor %}
    </ul>  

</div>    
{% endblock %}

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    Upload photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Upload photo" %}

    </div>
{% endblock content %} 

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update Photo" %}

    </div>
{% endblock content %} 

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}

    </div>
{% endblock content %} 

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked on_favs i18n %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}
    

{% block content %}

    <div class="container -mt-5 max-w-full flex h-75vh">
        <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.first_photo}});"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image: url({{photo.file.url}});" class="w-1/2 h-auto bg-cover bg-center border-gray-500 border"></div>                
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex mt-10 justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-600">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include 'mixins/user_avatar.html' with user=room.host h_and_w='w-16 h-16' %}
                    <span class="mt-1 text-gray-600">{{room.host.first_name}}</span>
                </a>
            </div>
            
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a class="block mb-10 w-2/5 text-green-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans "Remove from Favourites" %}</a>
            {% else %}
                <a class="block mb-10 w-2/5 text-green-600 font-bold" href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans "Save to Favourites" %}</a>
            {% endif %}
                
            <div class="border-section">
                <span class="mr-5">{{room.room_type}}</span>
                <span class="mr-5">{{room.beds}} bed{{room.beds|pluralize}}</span>
                <span class="mr-5">{{room.bedrooms}} bedsroom{{room.bedsrooms|pluralize}}</span>
                <span class="mr-5">{{room.baths}} bath{{room.baths|pluralize}}</span>
                <span class="mr-5">{{room.guests}} guest{{room.guests|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                {% for hr in room.house_rules.all %}
                    <li class="mb-2">{{hr}}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-green-500"></i>
                        <span class="font-bold text-lg ml-1">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-3"></div>
                    <div>
                        <span class="font-bold text-lg">{{room.reviews.count}}</span> 
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include 'mixins/user_avatar.html' with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-3">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20">
                            <span class="text-center font-semibold text-lg block mb-5">{{calendar.get_month}} / {{calendar.year}}</span>
                            <div class="cal-grid font-medium mb-4">
                                {% for day in calendar.day_names  %}
                                    <span>{{day}}</span>
                                {% endfor %}
                            </div>
                            <div class="cal-grid">
                                {% for day in calendar.get_days %}
                                    {% is_booked room day as is_booked_bool %}
                                    {% if day.number != 0 %}
                                        {% if day.past %}
                                            <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300">{{day}}</span>
                                        {% elif is_booked_bool %}
                                            <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300 line-through">{{day}}</span>
                                        {% else %}
                                            <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-green-400 hover:text-white hover:font-medium cursor-pointer">{{day}}</a>
                                        {% endif %}
                                    {% else %}
                                        <span></span>
                                    {% endif %}
                                
                                {% endfor %}
                                    
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                    
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-green-500 font-medium">Edit Photos</a>
        </div>
    </div>
{% endblock content %} 

templates/rooms/room_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block page_title %}
    Home
{% endblock page_title %}
    

{% block content %}

    <div class="container mx-auto max-w-5xl pb-10">

        <div class="container rounded-xl bg-gray-800 h-60vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(/static/img/greece.jpg)"></div>

        <div class="flex flex-wrap -mx-12 mb-10">
            {% for room in rooms %}
                {% include 'partials/room_card.html' with room=room %}
            {% endfor %}    
        </div>
        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-green-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>     
            {% endif %}

            <span class="mx-3 font-medium text-lg">
                {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages %}Page {{current_page}} of {{total_pages}}{% endblocktrans %}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-green-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %} 
        </div>
    </div>        
{% endblock content %}
    

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">
        
        <div class="my-10 w-full">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>
        {% for photo in room.photos.all %}
        <div class="mb-5  border p-6 border-gray-400 flex justify-between">
            <div class="flex items-start">
                <img src="{{photo.file.url}}" class="w-32 h-32">
                <span class="ml-5 text-lg">{{photo.caption}}</span>
            </div>
            <div class="flex flex-col w-1/5">
                <a class="btn-link mb-5 bg-green-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
            </div>
        </div>
        {% endfor %}
        
        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-green-500 font-medium text-xl">Back to edit room</a>
        </div>

    </div>
{% endblock content %} 

templates/rooms/search.html
{% extends 'base.html' %}


{% block page_title %}
    Search    
{% endblock page_title %}
    
{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<form action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <button>Search</button>
</form>

<h2>Results</h2>

{% for room in rooms %}
    <h4>{{room.name}}</h4>
{% endfor %}

{% if rooms.number >= 1 %}
    {% if rooms.has_previous %}
      <a href="{{ request.get_full_path }}&page={{rooms.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{rooms.number}} of {{rooms.paginator.num_pages}}

    {% if rooms.has_next %}
      <a href="{{ request.get_full_path }}&page={{rooms.next_page_number}}">Next</a>
    {% endif %}
{% endif %}

<hr />
        

{% endblock content %}
    