config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # / 으로 들어온 url에 관한 처리를 core/urls.py 에서 찾아 mapping 하라는 의미 이다.
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

# 내가 개발모드라면(Not production)
if settings.DEBUG:  # static 함수를 보면 (url, 사진저장폴더경로)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from unicodedata import name
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # name: 나중에 해당 url을 처리할때 url전부를 하드코딩하는 것 이 아니라, 간편하게 해당 url을 지칭할 수 있다.
    path("", room_views.HomeView.as_view(), name="home")
]

users/urls.py
from unicodedata import name
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SingUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update-password/",
        views.UpdatePasswordView.as_view(success_url=reverse_lazy("core:home")),
        name="update-password",
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    # clean()을 통해 에러 공통처리
    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)  # db에서 찾기
            if user.check_password(password):  # 해당 email을 가진 user model에서 password 체크
                return self.cleaned_data
            else:
                # add_error("필드", 에러): 해당 에러가 발생한 곳에서 에러 메시지 추가
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")

        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Name"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()


class UpdatePasswordForm(PasswordChangeForm):

    """ Update Passord Form Definition """

    old_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Current Password", "class": "form-btn rounded-t-lg"}
        ),
    )

    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "New Password", "class": "form-btn"}
        ),
    )
    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confrim New Password",
                "class": "form-btn rounded-b-lg",
            }
        ),
    )

users/views.py
import os
import requests
from config import settings
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


# mixins의 test가 true여야만 아래 코드를 진행가능
class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        # 이메일 인증 한 사람만 로그인 하게끔(custom)
        # check_user = models.User.objects.get(username=user)

        # if check_user.email_verified == False:
        #     print("please verify your email")
        if user is not None:
            messages.success(self.request, _(f"Welcome {user.first_name}"))
            login(self.request, user)
        return super().form_valid(form)

    # 로그아웃 시점에서 로그인이 필요한 요청을 한 경우  로그인을 시킨뒤
    # 아래 메서드 처럼 원래 요청을 수행할 수 있다.
    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, _("See you later"))
    logout(request)
    return redirect(reverse("core:home"))


class SingUpView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):  # form이 에러없이 유효하다면
        form.save()  # user를 생성하는 메소드
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        user.verify_email()
        return super().form_valid(form)


# 이메일 인증을 완료한 후 페이지
def complete_verification(request, key):
    try:
        # 해당 secret key 메일을 받은 user를 찾는다
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""  # 이메일 인증이 끝나면 secret 초기화
        user.save()
        # to do: add success message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


# 로그인 역할을 github로 보냄
def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"

    return redirect(  # github 인증을 요청하기 위해 request
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


# github에서 인증이 끝난 후 호출
def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            # github에 request를 보내서 code를 가지고 access_token을 얻는다
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please log in with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)


# kakao 로그인 요청
def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")  # 앱 REST API 키
    redirect_uri = (
        "http://127.0.0.1:8000/users/login/kakao/callback"  # 인가 코드가 리다이렉트될 URI
    )
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")  # 인가 코드 받기 요청으로 얻은 인가 코드
        client_id = os.environ.get("KAKAO_ID")  # 	앱 REST API 키
        redirect_uri = (
            "http://127.0.0.1:8000/users/login/kakao/callback"  # 인가 코드가 리다이렉트된 URI
        )
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()  # 토큰 json 얻기
        error = token_json.get("error", None)
        if error is not None:  # 에러가 발생했다면 예외
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")  # access_token 값 얻기
        profile_request = requests.get(  # 액세스 토큰으로 kakao user 정보 얻기
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()  # kakao user의 profile을 json 형식으로 받음
        email = profile_json.get("kakao_account").get("email")
        if email is None:
            raise KakaoException("Please also give me your email")
        properties = profile_json.get("properties")  # json에서 사용자의 정보 얻기
        nickname = properties.get("nickname")
        profile_image = (
            profile_json.get("kakao_account").get("profile").get("profile_image_url")
        )
        try:
            # 이미 카카오 id의 email과 같은 아이디가 db에 있는지
            user = models.User.objects.get(email=email)
            # 해당 user(중복 email)의 login_method가 kakao로 로그인 되어있는게 아니라면 예외
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(f"Please log in with: {user.login_method}")
        except models.User.DoesNotExist:  # 카카오로 로그인한 email이 db에 없다면
            user = models.User.objects.create(  # 주어진 정보로 user 생성
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:  # 프사가 있으면 얻기
                photo_request = requests.get(profile_image)

                user.avatar.save(
                    # file.save(파일 이름, 이미지 파일)
                    # ContentFile: 바이트코드로 이루어진 파일을 처리
                    f"{nickname}-avatar.jpg",
                    ContentFile(photo_request.content),
                )
        login(request, user)
        messages.success(request, f"Welcome back {user.first_name}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"

    # context 추가 가능
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["hello"] = "Hello"
    #     return context


# mixins.LoggedInOnlyView에 의해 로그인을 하지 않은 사람이 비번 변경등의 페이지를 요청하면
# 아래 클래스 코드 진행 안됨(프로필 업데이트)
class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"  # 반환할 템플릿 이름 지정
    fields = (
        "first_name",
        "last_name",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    )
    success_message = "Profile updated"  # message 띄우기

    # 수정하고 싶어하는 객체 반환
    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):

templates/users/login.html
{% extends 'base.html' %}


{% block page_title %}
    Log In
{% endblock page_title %}
    

{% block content %}

    <div class="container lg:w-5/12 md:w-7/12 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        
        {% include 'partials/social_login.html' %}    

        <form method="POST" action="{% url 'users:login' %}" class="w-full">
            {% csrf_token %}
            <input type="email" name="email" placeholder="&#xf0e0; &nbsp; Email" class="mb-3" style="font-family:Arial, FontAwesome">
            <input type="password" name="password" placeholder="&#xf023; &nbsp; Password" class="mb-3" style="font-family:Arial, FontAwesome">
            <button class="btn bg-red-500 text-white">
                <i class="fab fa-airbnb mr-2 fa-lg"></i> Login
            </button>
        </form>

        <div class="mt-5">
            <span class="mr-2 font-medium text-gray-600">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-green-500 font-medium">Sign up</a>
        </div>
    </div>

{% endblock content %}
    

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}
    

{% block content %}

<div class="container lg:w-5/12 md:w-7/12 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}  
    
        <form method="POST" action="{% url 'users:signup' %}" class="w-full">
            {% csrf_token %}

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <span class="text-red-700 font-medium text-sm">{{error}}</span> 
                {% endfor %}
            {% endif %}  
            
            
            {% for field in form %}
                <div class="input w-full {% if field.errors %}has_error{% endif %}">
                    {{field}}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <span class="text-red-700 font-medium text-sm">{{error}}</span> 
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
                

            <button class="btn bg-red-500 text-white">
                <i class="fab fa-airbnb mr-2 fa-lg"></i> Sign up
            </button>
        </form>

        <div class="mt-5">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-teal-500 font-medium">Log in</a>
        </div>

    </div>

{% endblock content %}
    

templates/users/update-password.html
{% extends 'base.html' %}


{% block page_title %}
    Update Password
{% endblock page_title %}
    

{% block content %}
<div class="min-h-75vh">
    <div class="container lg:w-5/12 md:w-7/12 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        <form method="POST" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <span class="text-red-700 font-medium text-sm">{{error}}</span> 
                {% endfor %}
            {% endif %}
            
            {% for field in form %}
                {% include 'mixins/auth/form_input.html' with field=field %}
            {% endfor %}

            <button class="btn bg-red-500 text-white">Update Password</button>
        </form>
    </div>
</div>

{% endblock content %}
    

templates/users/update-profile.html
{% extends 'base.html' %}


{% block page_title %}
    Update Profile
{% endblock page_title %}
    

{% block content %}

    <div class="container lg:w-5/12 md:w-7/12 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">


        <form method="POST" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <span class="text-red-700 font-medium text-sm">{{error}}</span> 
                {% endfor %}
            {% endif %}
            
            {% for field in form %}
                {{field.name}}
                {% include 'mixins/auth/form_input.html' with field=field %}
            {% endfor %}

            <button class="btn bg-red-500 text-white">Update Profile</button>
        </form>

        
        {% if object.login_method == "email" %}
            <div class="mt-5">
                <a href="{% url 'users:update-password' %}" class="text-green-500 font-medium">Change Password</a>
            </div>
        {% endif %}
            
    </div>

{% endblock content %}
    

templates/users/user_detail.html
{% extends 'base.html' %}


{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}
    

{% block content %}

    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-7/12 xl:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/user_avatar.html' with user=user_obj h_and_w='w-32 h-32' text='text-6xl' height='h-profile_text' %}
    
            <div class="flex items-center">
                <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
                {% if user_obj.superhost %}
                    <i class="fas fa-check-circle text-lg text-green-400 ml-1"></i>
                {% endif %}
            </div>
    
            <span class="text-lg mb-5">{{user_obj.bio}}</span>
    
            {% if user == user_obj %}
                <a href="{% url 'users:update' %}" class="btn-link">Edit Profile</a>
            {% endif %}
        </div>
    
        {% if user_obj.rooms.count > 0 %}
            <div class="container mx-auto pb-10 flex flex-col items-center">
                <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Rooms</h3>
                <div class="flex flex-wrap -mx-40 mb-10 w-full">
                    {% for room in user_obj.rooms.all %}
                        {% include 'partials/room_card.html' with room=room %}
                    {% endfor %}    
                </div>
            </div>
        {% endif %}
    </div>
        
    
{% endblock content %}
    